# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/

version: "2"

run:
  # Timeout for analysis, e.g. 30s, 5m. Default is 1m.
  timeout: 15m
  
  # Include test files or not.
  tests: true
  
  # Build tags to use
  build-tags: []
  
  # Which dirs to exclude: issues from them won't be reported.
  exclude-dirs:
    - vendor
    - scripts
    - docs
    - .git
  
  # Which files to exclude: they will be analyzed, but issues from them won't be reported.
  exclude-files:
    - ".*\\.pb\\.go$"

linters:
  # Enable specific linters (disabled some slower ones for CI performance)
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - revive
  # Disabled gocritic for now due to performance - can re-enable if needed
  disable:
    - gocritic

issues:
  # The maximum number of issues per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  
  # The maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

