# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/

version: "2"

run:
  # Timeout for analysis, e.g. 30s, 5m. Default is 1m.
  timeout: 15m
  
  # Include test files or not.
  tests: true
  
  # Build tags to use
  build-tags: []

linters:
  # Enable specific linters (disabled some slower ones for CI performance)
  # Note: gosimple is merged into staticcheck in v2.x
  # Note: gofmt and goimports are formatters, not linters in v2.x - use 'go fmt' and 'goimports' commands directly
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - revive
  # Disabled gocritic for now due to performance - can re-enable if needed
  disable:
    - gocritic

issues:
  # The maximum number of issues per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  
  # The maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

