# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/

version: "2"

run:
  # Timeout for analysis
  timeout: 10m
  
  # Exclude test files from linting in CI (set to false)
  # This speeds up CI significantly - developers should lint tests locally
  tests: false
  
  # Build tags to use
  build-tags: []

linters:
  # Enable specific linters (disabled some slower ones for CI performance)
  # Note: gosimple is merged into staticcheck in v2.x
  # Note: gofmt and goimports are formatters, not linters in v2.x - use 'go fmt' and 'goimports' commands directly
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - revive
  # Disabled gocritic for performance - can re-enable selectively if needed
  disable:
    - gocritic

issues:
  # Maximum issues per linter (prevents one linter from overwhelming output)
  max-issues-per-linter: 50
  
  # Maximum duplicate issues (prevents same error repeated many times)
  max-same-issues: 5

