# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/

version: "2"

run:
  # Timeout for analysis
  timeout: 10m
  
  # Exclude test files from linting in CI (set to false)
  # This speeds up CI significantly - developers should lint tests locally
  tests: false
  
  # Build tags to use
  build-tags: []

linters:
  # Focus on bug-catching linters only (see docs/LINTING_PHILOSOPHY.md)
  # Note: gosimple is merged into staticcheck in v2.x
  # Note: gofmt and goimports are formatters, not linters in v2.x
  #       Formatting is checked separately in CI and pre-commit hooks
  enable:
    # Bug-catching linters (keep these)
    - errcheck      # Unchecked errors - catches real bugs
    - govet         # Go vet checks - catches real bugs
    - staticcheck   # Advanced static analysis - catches logic errors
    - ineffassign   # Ineffectual assignments - catches dead code
    - unused        # Unused code - catches dead code (can be noisy, but useful)
  disable:
    # Style-only linters (disabled to reduce friction)
    - gocritic      # Performance - disabled for CI speed
    - revive        # Style - package comments, unused params (interface compliance)
    - unparam       # Style - unused parameters (often false positives for interfaces)
    - misspell      # Style - spelling checker
    - unconvert     # Style - type conversions (often false positives)

issues:
  # Maximum issues per linter (prevents one linter from overwhelming output)
  max-issues-per-linter: 50
  
  # Maximum duplicate issues (prevents same error repeated many times)
  max-same-issues: 5

