#!/bin/bash
# LlamaGate One-Click Binary Installer for Unix/Linux/macOS
# Downloads and sets up the pre-built binary - no Go required!

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Detect OS and architecture
detect_platform() {
    local os=""
    local arch=""
    
    case "$(uname -s)" in
        Linux*)     os="linux" ;;
        Darwin*)    os="darwin" ;;
        *)          os="linux" ;;
    esac
    
    case "$(uname -m)" in
        x86_64)     arch="amd64" ;;
        arm64|aarch64) arch="arm64" ;;
        *)          arch="amd64" ;;
    esac
    
    echo "${os}-${arch}"
}

PLATFORM=$(detect_platform)
BINARY_NAME="llamagate-${PLATFORM}"
TARGET_NAME="llamagate"

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TARGET_PATH="$PROJECT_ROOT/$TARGET_NAME"

# Latest release URL
LATEST_RELEASE_URL="https://github.com/smcdaniel54/LlamaGate/releases/latest/download/$BINARY_NAME"

echo "========================================"
echo -e "${CYAN}LlamaGate Binary Installer${NC}"
echo "========================================"
echo ""

echo -e "${YELLOW}[1/3]${NC} Detecting platform..."
echo "  Platform: $PLATFORM" | sed 's/-/ /g' | awk '{print "  " $1 " (" $2 ")"}'
echo ""

echo -e "${YELLOW}[2/3]${NC} Downloading LlamaGate binary..."
echo "  URL: $LATEST_RELEASE_URL" | sed 's/.*\///' | sed 's/^/  /'

# Check for curl or wget
if command -v curl >/dev/null 2>&1; then
    DOWNLOAD_CMD="curl -L -o"
elif command -v wget >/dev/null 2>&1; then
    DOWNLOAD_CMD="wget -O"
else
    echo -e "${RED}✗${NC} Neither curl nor wget found. Please install one of them."
    exit 1
fi

# Download
if $DOWNLOAD_CMD "$TARGET_PATH" "$LATEST_RELEASE_URL" 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Download complete"
else
    echo -e "${RED}✗${NC} Download failed"
    echo ""
    echo "Please download manually from:"
    echo -e "${CYAN}  https://github.com/smcdaniel54/LlamaGate/releases/latest${NC}"
    exit 1
fi

# Make executable
chmod +x "$TARGET_PATH"

# Verify
if [ -f "$TARGET_PATH" ]; then
    FILE_SIZE=$(du -h "$TARGET_PATH" | cut -f1)
    echo -e "${GREEN}✓${NC} Binary verified ($FILE_SIZE)"
else
    echo -e "${RED}✗${NC} Binary not found"
    exit 1
fi

echo ""
echo -e "${YELLOW}[3/3]${NC} Creating .env file..."
ENV_FILE="$PROJECT_ROOT/.env"
if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" <<EOF
# LlamaGate Configuration
# Generated by installer on $(date '+%Y-%m-%d %H:%M:%S')

# Ollama server URL
OLLAMA_HOST=http://localhost:11434

# API key for authentication (leave empty to disable authentication)
API_KEY=

# Rate limit (requests per second)
RATE_LIMIT_RPS=50

# Enable debug logging (true/false)
DEBUG=false

# Server port
PORT=11435

# Log file path (leave empty to log only to console)
LOG_FILE=
EOF
    echo -e "${GREEN}✓${NC} Created .env file with defaults"
else
    echo -e "${YELLOW}⚠${NC} .env file already exists, skipping"
fi

echo ""
echo "========================================"
echo -e "${GREEN}Installation Complete!${NC}"
echo "========================================"
echo ""
echo "Binary location: $TARGET_PATH" | sed 's/^/  /'
echo ""
echo -e "${YELLOW}To run LlamaGate:${NC}"
echo -e "${CYAN}  cd $PROJECT_ROOT${NC}"
echo -e "${CYAN}  ./$TARGET_NAME${NC}"
echo ""
echo -e "${YELLOW}Or use the run script:${NC}"
echo -e "${CYAN}  ./scripts/unix/run.sh${NC}"
echo ""

