#!/bin/bash
# LlamaGate One-Click Binary Installer for Unix/Linux/macOS
# Downloads and sets up the pre-built binary - no Go required!

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Detect OS and architecture
detect_platform() {
    local os=""
    local arch=""
    
    case "$(uname -s)" in
        Linux*)     os="linux" ;;
        Darwin*)    os="darwin" ;;
        *)          os="linux" ;;
    esac
    
    case "$(uname -m)" in
        x86_64)     arch="amd64" ;;
        arm64|aarch64) arch="arm64" ;;
        *)          arch="amd64" ;;
    esac
    
    echo "${os}-${arch}"
}

PLATFORM=$(detect_platform)
BINARY_NAME="llamagate-${PLATFORM}"
TARGET_NAME="llamagate"

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TARGET_PATH="$PROJECT_ROOT/$TARGET_NAME"

# Latest release URL
LATEST_RELEASE_URL="https://github.com/smcdaniel54/LlamaGate/releases/latest/download/$BINARY_NAME"

echo "========================================"
echo -e "${CYAN}LlamaGate Binary Installer${NC}"
echo "========================================"
echo ""

echo -e "${YELLOW}[1/3]${NC} Detecting platform..."
echo "  Platform: $PLATFORM" | sed 's/-/ /g' | awk '{print "  " $1 " (" $2 ")"}'
echo ""

echo -e "${YELLOW}[2/3]${NC} Downloading LlamaGate binary..."
echo "  URL: $LATEST_RELEASE_URL" | sed 's/.*\///' | sed 's/^/  /'

# Check for curl or wget
if command -v curl >/dev/null 2>&1; then
    DOWNLOAD_CMD="curl -L -o"
elif command -v wget >/dev/null 2>&1; then
    DOWNLOAD_CMD="wget -O"
else
    echo -e "${RED}✗${NC} Neither curl nor wget found. Please install one of them."
    exit 1
fi

# Download
HTTP_CODE=0
if command -v curl >/dev/null 2>&1; then
    HTTP_CODE=$(curl -sL -o "$TARGET_PATH" -w "%{http_code}" "$LATEST_RELEASE_URL" 2>/dev/null || echo "000")
elif command -v wget >/dev/null 2>&1; then
    HTTP_CODE=$(wget -q -O "$TARGET_PATH" --server-response "$LATEST_RELEASE_URL" 2>&1 | awk '/HTTP/{print $2}' | tail -1 || echo "000")
fi

if [ "$HTTP_CODE" = "200" ] && [ -f "$TARGET_PATH" ] && [ -s "$TARGET_PATH" ]; then
    echo -e "${GREEN}✓${NC} Download complete"
elif [ "$HTTP_CODE" = "404" ]; then
    echo -e "${RED}✗${NC} Binary not found (404) - Pre-built binaries are not yet available"
    echo ""
    echo "Options:"
    echo -e "${CYAN}  1.${NC} Build from source using the source installer:"
    echo -e "${GRAY}     ./install/unix/install.sh${NC}"
    echo ""
    echo -e "${CYAN}  2.${NC} Wait for binaries to be published to releases:"
    echo -e "${GRAY}     https://github.com/smcdaniel54/LlamaGate/releases${NC}"
    echo ""
    echo -e "${CYAN}  3.${NC} Build manually:"
    echo -e "${GRAY}     go build -o llamagate ./cmd/llamagate${NC}"
    exit 1
else
    echo -e "${RED}✗${NC} Download failed (HTTP $HTTP_CODE)"
    echo ""
    echo "Please try again or download manually from:"
    echo -e "${CYAN}  https://github.com/smcdaniel54/LlamaGate/releases/latest${NC}"
    exit 1
fi

# Make executable
chmod +x "$TARGET_PATH"

# Verify
if [ -f "$TARGET_PATH" ]; then
    FILE_SIZE=$(du -h "$TARGET_PATH" | cut -f1)
    echo -e "${GREEN}✓${NC} Binary verified ($FILE_SIZE)"
else
    echo -e "${RED}✗${NC} Binary not found"
    exit 1
fi

echo ""
echo -e "${YELLOW}[3/3]${NC} Creating .env file..."
ENV_FILE="$PROJECT_ROOT/.env"
if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" <<EOF
# LlamaGate Configuration
# Generated by installer on $(date '+%Y-%m-%d %H:%M:%S')

# Ollama server URL
OLLAMA_HOST=http://localhost:11434

# API key for authentication
# Set to sk-llamagate to match documentation examples
# IMPORTANT: Change this to a secure key for production use
# Leave empty to disable authentication
API_KEY=sk-llamagate

# Rate limit (requests per second)
RATE_LIMIT_RPS=50

# Enable debug logging (true/false)
DEBUG=false

# Server port
PORT=11435

# Log file path (leave empty to log only to console)
LOG_FILE=
EOF
    echo -e "${GREEN}✓${NC} Created .env file with defaults"
else
    echo -e "${YELLOW}⚠${NC} .env file already exists, skipping"
fi

echo ""
echo "========================================"
echo -e "${GREEN}Installation Complete!${NC}"
echo "========================================"
echo ""
echo "Binary location: $TARGET_PATH" | sed 's/^/  /'
echo ""
echo -e "${YELLOW}To run LlamaGate:${NC}"
echo -e "${CYAN}  cd $PROJECT_ROOT${NC}"
echo -e "${CYAN}  ./$TARGET_NAME${NC}"
echo ""
echo -e "${YELLOW}Or use the run script:${NC}"
echo -e "${CYAN}  ./scripts/unix/run.sh${NC}"
echo ""

