# LlamaGate One-Click Binary Installer for Windows
# Downloads and sets up the pre-built binary - no Go required!

$ErrorActionPreference = "Stop"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "LlamaGate Binary Installer" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Detect architecture
$arch = "amd64"  # Default, can be extended for ARM64 if needed
$binaryName = "llamagate-windows-amd64.exe"
$targetName = "llamagate.exe"

# Get latest release URL
$latestReleaseUrl = "https://github.com/smcdaniel54/LlamaGate/releases/latest/download/$binaryName"
$targetPath = Join-Path $PSScriptRoot "..\..\$targetName"

Write-Host "[1/3] Downloading LlamaGate binary..." -ForegroundColor Yellow
Write-Host "  URL: $latestReleaseUrl" -ForegroundColor Gray

try {
    # Download the binary
    $response = Invoke-WebRequest -Uri $latestReleaseUrl -OutFile $targetPath -UseBasicParsing -ErrorAction Stop
    Write-Host "  [OK] Download complete" -ForegroundColor Green
} catch {
    $statusCode = $_.Exception.Response.StatusCode.value__
    if ($statusCode -eq 404) {
        Write-Host "  [ERROR] Binary not found (404) - Pre-built binaries are not yet available" -ForegroundColor Red
        Write-Host ""
        Write-Host "Options:" -ForegroundColor Yellow
        Write-Host "  1. Build from source using the source installer:" -ForegroundColor Cyan
        Write-Host "     install\windows\install.ps1" -ForegroundColor Gray
        Write-Host ""
        Write-Host "  2. Wait for binaries to be published to releases:" -ForegroundColor Cyan
        Write-Host "     https://github.com/smcdaniel54/LlamaGate/releases" -ForegroundColor Gray
        Write-Host ""
        Write-Host "  3. Build manually:" -ForegroundColor Cyan
        Write-Host "     go build -o llamagate.exe ./cmd/llamagate" -ForegroundColor Gray
    } else {
        Write-Host "  [ERROR] Download failed: $_" -ForegroundColor Red
        Write-Host ""
        Write-Host "Please try again or download manually from:" -ForegroundColor Yellow
        Write-Host "  https://github.com/smcdaniel54/LlamaGate/releases/latest" -ForegroundColor Cyan
    }
    exit 1
}

Write-Host ""
Write-Host "[2/3] Verifying binary..." -ForegroundColor Yellow
if (Test-Path $targetPath) {
    $fileSize = (Get-Item $targetPath).Length
    Write-Host "  [OK] Binary verified ($([math]::Round($fileSize/1MB, 2)) MB)" -ForegroundColor Green
} else {
    Write-Host "  [ERROR] Binary not found" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "[3/3] Creating .env file..." -ForegroundColor Yellow
$envFile = Join-Path $PSScriptRoot "..\..\.env"
if (-not (Test-Path $envFile)) {
    $envContent = @"
# LlamaGate Configuration
# Generated by installer on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# Ollama server URL
OLLAMA_HOST=http://localhost:11434

# API key for authentication (leave empty to disable authentication)
API_KEY=

# Rate limit (requests per second)
RATE_LIMIT_RPS=50

# Enable debug logging (true/false)
DEBUG=false

# Server port
PORT=11435

# Log file path (leave empty to log only to console)
LOG_FILE=
"@
    $envContent | Out-File -FilePath $envFile -Encoding UTF8
    Write-Host "  [OK] Created .env file with defaults" -ForegroundColor Green
} else {
    Write-Host "  [SKIP] .env file already exists, skipping" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Installation Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Binary location: $targetPath" -ForegroundColor Gray
Write-Host ""
Write-Host "To run LlamaGate:" -ForegroundColor Yellow
Write-Host "  cd $(Split-Path $targetPath -Parent)" -ForegroundColor Cyan
Write-Host "  .\$targetName" -ForegroundColor Cyan
Write-Host ""
Write-Host "Or use the run script:" -ForegroundColor Yellow
Write-Host '  scripts\windows\run.cmd' -ForegroundColor Cyan
Write-Host ""

